version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
workflows:
  build-and-push:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_REGION
          repo: nginx
          tag: ${CIRCLE_SHA1}
