version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
workflows:
  build-and-push:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: 089207428304.dkr.ecr.ap-northeast-1.amazonaws.com
          region: ap-northeast-1
          repo: nginx
          tag: ${CIRCLE_SHA1}
